# [AI GENERATED] This file was written by the assistant.
from typing import TypedDict
from langchain_core.prompts import PromptTemplate

class MistralOutput(TypedDict):
    summary: str
    confidence: float

output = MistralOutput(summary="This is a summary generated by Mistral.", confidence=0.95)

template = PromptTemplate(
    template="Summary: {summary}\nConfidence: {confidence}",
    input_variables=["summary", "confidence"],
    validate_template=True
)

prompt = template.invoke(output)
print(prompt)
